server:
  port: 80
  servlet:
    context-path: /api

spring:
  application:
    name: uniex-gateway

  cloud:
    gateway:
      routes:
      - id: 163_route
        uri: http://www.163.com/
        predicates:
        - Path=/163

      - id: baidu_route
        uri: http://www.baidu.com
        predicates:
        - Path=/baidu

      - id: google_route
        uri: http://www.aliyun.com
        predicates:
        - Path=/google

      - id: ratelimiter_route
        uri: lb://pigx-upms
        order: 10000
        predicates:
        - Path=/admin/**
        filters:
        - name: RequestRateLimiter
          ages:
            redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
            redis-rate-limiter.burstCapacity: 3  # 流速 每秒
            key-resolver: "#{@remoteAddrKeyResolver}" #SPEL表达式去的对应的bean
        - StripPrefix=1